export const Types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    RESGISTER_SUCCESS: 'RESGISTER_SUCCESS',
    RESGISTER_FAILED: 'RESGISTER_FAILED',

    GET_LOGIN_REQUEST: 'GET_LOGIN_REQUEST',
    GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
    GET_LOGIN_FAILED: 'GET_LOGIN_FAILED',
}